/******** DO NOT EDIT THIS FILE ********/
#ifndef _RFT_CLIENT_LOGGING_H
#define _RFT_CLIENT_LOGGING_H
#include "rft_client_util.h"

/*
 * exit_err(char* src_file, int src_line, protocol_t* proto) 
 *      - exit the client with an error message output to stderr for execution
 *      from given source code file at given source code line dbased on the
 *      current state of the protocol as specified by the given proto struct.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void exit_err(char* src_file, int src_line, protocol_t* proto);

/*
 * log_protocol(char* src_file, int src_line, protocol_t* proto) 
 *      - log information for execution from given source code file at given 
 *      source code line for current state of the  protocol as specified by the 
 *      given proto struct.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void log_protocol(char* src_file, int src_line, protocol_t* proto);

/*
 * log_separator() - log a separator 
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void log_separator(protocol_t* proto);

#endif