/******** DO NOT EDIT THIS FILE ********/
#define MUNIT_ENABLE_ASSERT_ALIASES
#include <stdio.h>
#include <math.h>
#include <arpa/inet.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>

#include "munit.h"
#include "rft_client_util.h"

static MunitResult test_set_udp_socket(const MunitParameter params[], 
    void* fixture);
static MunitResult test_set_udp_socket_err(const MunitParameter params[], 
    void* fixture);
    
static MunitTest tests[] = {
    { "/test_set_udp_socket", test_set_udp_socket, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_set_udp_socket_err", test_set_udp_socket_err, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
        
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_rftcu_set_udp_socket", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static MunitResult test_set_udp_socket(const MunitParameter params[], 
    void* fixture) {
    char* server_addr;
    protocol_t proto;
    
    proto.sockfd = -1;
    server_addr = "127.0.0.1";
    
    snprintf(proto.server_addr, MAX_FILENAME_SIZE, "%s", server_addr);
    assert_string_equal(proto.server_addr, server_addr);
        
    proto_state ps = set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_TFR_READY);
    assert_int(proto.sockfd, !=, -1);
    close(proto.sockfd);

    proto.state = PS_INIT;
    proto.sockfd = -1;
    server_addr = "128.240.212.56";
    
    snprintf(proto.server_addr, MAX_FILENAME_SIZE, "%s", server_addr);
    assert_string_equal(proto.server_addr, server_addr);
        
    ps = set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_TFR_READY);
    close(proto.sockfd);
 
    proto.sockfd = -1;
    server_addr = "128";
    
    snprintf(proto.server_addr, MAX_FILENAME_SIZE, "%s", server_addr);
    assert_string_equal(proto.server_addr, server_addr);
        
    ps = set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_TFR_READY);
    close(proto.sockfd);

    return MUNIT_OK;
}

static MunitResult test_set_udp_socket_err(const MunitParameter params[], 
    void* fixture) {
    char* server_addr;
    protocol_t proto;
    
    proto.sockfd = -1;
    memset(proto.server_addr, 0, MAX_FILENAME_SIZE);
        
    proto_state ps = set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_BAD_SERVER);
    
    server_addr = "cs-linux.ncl.ac.uk";
    snprintf(proto.server_addr, MAX_FILENAME_SIZE, "%s", server_addr);
    assert_string_equal(proto.server_addr, server_addr);
    
    ps = set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_BAD_SERVER);

    server_addr = "invalid_addr";
    snprintf(proto.server_addr, MAX_FILENAME_SIZE, "%s", server_addr);
    assert_string_equal(proto.server_addr, server_addr);
    set_udp_socket(&proto);
    
    assert_int(ps, ==, PS_BAD_SERVER);

    return MUNIT_OK;
}

