/******** DO NOT EDIT THIS FILE ********/
#define MUNIT_ENABLE_ASSERT_ALIASES
#include <stdio.h>
#include <math.h>
#include <arpa/inet.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>

#include "munit.h"
#include "rft_client_util.h"

static MunitResult test_set_socket_timeout(const MunitParameter params[], 
    void* fixture);
static MunitResult test_set_socket_timeout_err(const MunitParameter params[], 
    void* fixture);

static MunitTest tests[] = {
    { "/test_set_socket_timeout", test_set_socket_timeout, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_set_socket_timeout_err", test_set_socket_timeout_err, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },

    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_rftcu_set_socket_timeout", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static MunitResult test_set_socket_timeout(const MunitParameter params[], 
    void* fixture) {    
    protocol_t proto;
    struct timeval timeout;
    socklen_t to_size = sizeof(struct timeval);     
    timeout.tv_sec = 0;
    timeout.tv_usec = 0;

    memset(&proto, 0, sizeof(protocol_t));
    proto.sockfd = socket(AF_INET, SOCK_DGRAM, 0);
    proto.timeout_sec = DEFAULT_TIMEOUT;
    
    proto_state ps = set_socket_timeout(&proto);
    
    assert_int(ps, ==, PS_SOCKTOUT_SET);
    
    getsockopt(proto.sockfd, SOL_SOCKET, SO_RCVTIMEO, &timeout, &to_size);
        
    assert_int(timeout.tv_sec, ==, DEFAULT_TIMEOUT);
    assert_int(timeout.tv_usec, ==, 0);
    assert_ulong(to_size, ==, sizeof(struct timeval));

    proto.timeout_sec = 2;
    
    ps = set_socket_timeout(&proto);
    
    assert_int(ps, ==, PS_SOCKTOUT_SET);
        
    getsockopt(proto.sockfd, SOL_SOCKET, SO_RCVTIMEO, &timeout, &to_size);
    
    close(proto.sockfd);
    
    assert_int(timeout.tv_sec, ==, 2);
    assert_int(timeout.tv_usec, ==, 0);
    assert_ulong(to_size, ==, sizeof(struct timeval));

    close(proto.sockfd);

    return MUNIT_OK;
}

static MunitResult test_set_socket_timeout_err(const MunitParameter params[], 
    void* fixture) {    
    protocol_t proto;

    memset(&proto, 0, sizeof(protocol_t));
    proto.sockfd = socket(AF_INET, SOCK_DGRAM, 0);
    proto.timeout_sec = DEFAULT_TIMEOUT;

    close(proto.sockfd);

    assert_int(set_socket_timeout(&proto), ==, PS_BAD_SOCKTOUT);
    
    return MUNIT_OK;
}

